name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger on push to main

permissions:
  contents: write  # Needed to push to gh-pages branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Generate env.js with secrets
      - name: Create env.js
        run: |
          echo "window.GOOGLE_CLIENT_ID = '${{ secrets.GOOGLE_CLIENT_ID }}';" > env.js
          echo "window.GOOGLE_API_KEY = '${{ secrets.GOOGLE_API_KEY }}';" >> env.js

      # Deploy current directory (including env.js, HTML, JS, CSS) to gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .                # Deploy root directory (where env.js lives)
          publish_branch: gh-pages     # Branch GitHub Pages is publishing from